### PR TITLE
add php 8 to supported versions

### PR DESCRIPTION
**Pull request by akurov-lam**

### CODE REVIEW

**Review by scaytrase — CHANGES_REQUESTED** [review]
New environment should be added for test runs. Currently new environment is not tested strictly (only with allow failures nightly)

**Comment by scaytrase** [comment]
And it's failing https://travis-ci.org/github/lamoda/php-enum-bundle/jobs/759309954

**Comment by akurov-lam** [comment]
If we add php 8 we have to update phpunit to 8 at least. But phpunit 8 requires at least php 7.2 so we can't test against php 7.1. What should I do?

**Comment by scaytrase** [comment]
You can require multiple versions of phpunit with `"phpnuit/phpunit": "^7.5 || ^8 || ^9". Composer choose the best fit. Your code (tests) should conform all of the required versions in this case

**Review by scaytrase — APPROVED** [review]
LGTM 👍

**Comment by scaytrase** [comment]
https://github.com/lamoda/php-enum-bundle/releases/tag/1.3

**Pull request merged**
